Integrate Codeclimate
cs169/BJC-Teacher-Tracker pull request #6
Opened 2023-03-01 21:28 UTC by Reimirno

Downgrade simplecov to below 0.17.1
Removed cobertura

2023-03-02 03:16 UTC, Reimirno commented
Thanks to Professor Ball's help this is resolved.

We downgraded `simplecov` to 0.17.1 (the last version without compatibility issue).

I fixed a few syntax issues and made some necessary changes in response to the downgrade. 

Now it should be all fine to merge.

2023-03-06 05:57 UTC, cycomachead commented on spec/rails_helper.rb
> +# require "simplecov-cobertura"
```suggestion
```

2023-03-06 05:59 UTC, cycomachead requested changes
Looks good, but let's just delete the references to coberturra. 
(you can commit all the suggestions in a batch)

2023-03-06 05:59 UTC, cycomachead commented on spec/rails_helper.rb
> +# SimpleCov.formatter = SimpleCov::Formatter::CoberturaFormatter
```suggestion
```

2023-03-06 05:59 UTC, cycomachead commented on features/support/env.rb
> +# require "simplecov-cobertura"
```suggestion
```

2023-03-06 05:59 UTC, cycomachead commented on features/support/env.rb
> +  #     SimpleCov::Formatter::CoberturaFormatter,
```suggestion
```

2023-03-06 05:59 UTC, cycomachead commented on README.md
> +
```suggestion
### CodeClimate Local Test
```

2023-03-06 05:59 UTC, cycomachead commented on Gemfile
> +  # gem "simplecov-cobertura", require: false
```suggestion
```

2023-03-08 19:11 UTC, Reimirno commented
Committed all the suggestions and squashed.
(I didn't know you could commit suggestions in batch, Ugh. I will do that next time)

2023-03-08 23:32 UTC, merged